name: >
    Build 2GP Feature Test Package
on:
    workflow_dispatch:
    push:
        branches:
            - feature/**
            - main
jobs:
    feature-test:
        name: "Create 2GP Package Version"
        uses: muselab-d2x/d2x/.github/workflows/build-feature-test-package.yml@cumulusci-next-snapshots
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.CCI_GITHUB_TOKEN }}"
