name: >
  2GP Feature Test and Snapshot
on:
    workflow_dispatch:
    push:
        branches:
            - feature/**
            - main
jobs:     
    feature-test:
        name: "Feature Test"
        uses: muselab-d2x/d2x/.github/workflows/feature-test-snapshot.yml@cumulusci-next-snapshots
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.CCI_GITHUB_TOKEN }}"
