name: >
    Unmanaged Feature Test Using Predicted Snapshots
on:
    workflow_dispatch:
    workflow_run:
        workflows:
            - Build Feature Test Package
        types:
            - completed
jobs:
    feature-test:
        name: "Feature Test"
        uses: muselab-d2x/d2x/.github/workflows/feature-test.yml@cumulusci-next-snapshots
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.CCI_GITHUB_TOKEN }}"