name: >
    Unmanaged Feature Test With PR Snapshot Creation
on:
    workflow_dispatch:
    push:
        branches:
            - feature/**
            - main
jobs:
    feature-test:
        name: "Feature Test"
        uses: muselab-d2x/d2x/.github/workflows/feature-test-snapshot.yml@cumulusci-next-snapshots
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.CCI_GITHUB_TOKEN }}"
            github-app-id: "${{ secrets.CCI_GITHUB_APP_ID }}"
            github-app-key: "${{ secrets.CCI_GITHUB_APP_KEY }}"
        with:
            create_pr_snapshot: true
            create_failure_snapshot: true
            create_snapshot_commit_status: true
