name: Create Org from Snapshot
on:
    workflow_dispatch:
        inputs:
            environment_name:
                description: "The name of the org to create. Must be a valid GitHub Environment name."
                required: true
                type: string
            org_config:
                description: "The CumulusCI org name to use as the base configuration"
                required: true
                default: "feature"
                type: string
            snapshot_name:
                description: "The name of the snapshot to use to create the org"
                required: true
jobs:
    create-org:
        uses: muselab-d2x/d2x/.github/workflows/org-from-snapshot.yml@cumulusci-next-snapshots
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            # github-app-id: "${{ secrets.CCI_GITHUB_APP_ID }}"
            # github-app-key: "${{ secrets.CCI_GITHUB_APP_KEY }}"
            github-token: "${{ secrets.CCI_GITHUB_TOKEN}}"
        with:
            org_name: ${{ github.event.inputs.org_config }}
            snapshot_name: ${{ github.event.inputs.snapshot_name }}
            environment_name: ${{ github.event.inputs.environment_name }}
