name: Get Slack DM With Org Login URL
on:
    workflow_dispatch:
        inputs:
            org:
                description: "The name of the org to get the login URL for. NOTE: Do not select orgs staring with `Snapshot:`"
                required: true
                type: environment
            slack_username:
                description: "The Slack username to send the DM to"
                required: true
                type: string
jobs:
    check-auth-url:
        runs-on: ubuntu-latest
        environment: ${{ inputs.org }}
        steps:
            - name: Check SFDX_AUTH_URL for Environment
              run: |
                  python -c "import os; print('force' in os.environ['SFDX_AUTH_URL'])"
                  python -c "print('tasks:' in open('cumulusci.yml','r').read())"
                  echo "SFDX_AUTH_URL: ${SFDX_AUTH_URL}"
                  echo "${SFDX_AUTH_URL}" > auth_url.txt
                  echo "Length: `wc -c auth_url.txt`"
                  grep "force:" auth_url.txt
                  grep "PlatformCLI" auth_url.txt
              env:
                  SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
    generate-login-url:
        runs-on: ubuntu-latest
        environment: ${{ inputs.org }}
        container:
            image: ghcr.io/muselab-d2x/d2x:cumulusci-next-snapshots
            options: --user root
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Check SFDX_AUTH_URL for Environment
              run: |
                  echo "SFDX_AUTH_URL: ${SFDX_AUTH_URL}"
                  python -c "import os; print('force' in os.environ['SFDX_AUTH_URL'])"
                  python -c "print('tasks:' in open('cumulusci.yml','r').read())"
                  echo "${SFDX_AUTH_URL}" > auth_url.txt
                  echo "Length: `wc -c auth_url.txt`"
                  grep "^force://.*$" auth_url.txt
                  grep "PlatformCLI" auth_url.txt
              env:
                  SFDX_AUTH_URL: ${{ secrets.sfdx-auth-url }}
            - name: Generate Login URL for ${{ inputs.org }}
              env:
                  SFDX_AUTH_URL: ${{ secrets.sfdx-auth-url }}
              run: |
                  echo "${SFDX_AUTH_URL}" > auth.url
                  echo "SFDX AUTH URL is `wc -l auth.url` lines long"
                  sf org login sfdx-url -f auth.url
                  sf org open -r --json | jq -r '.result.url' > login_url.txt

    send-login-url:
        needs: check-auth-url
        uses: muselab-d2x/d2x/.github/workflows/org-login-slack.yml@cumulusci-next-snapshots
        with:
            environment: ${{ inputs.org }}
            slack_username: ${{ github.event.inputs.slack_username }}
        secrets: inherit
