name: Get Slack DM With Org Login URL
on:
    workflow_dispatch:
        inputs:
            org:
                description: "The name of the org to get the login URL for. NOTE: Do not select orgs staring with `Snapshot:`"
                required: true
                type: environment
            slack_username:
                description: "The Slack username to send the DM to"
                required: true
                type: string
jobs:
    check-auth-url:
        runs-on: ubuntu-latest
        environment: ${{ inputs.org }}
        steps:
            - name: Check SFDX_AUTH_URL for Environment
              run: |
                  echo "SFDX_AUTH_URL: ${SFDX_AUTH_URL}"
                  echo "${SFDX_AUTH_URL}" > auth_url.txt
                  echo "Length: `wc -c auth_url.txt`"
              env:
                  SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
    send-login-url:
        uses: muselab-d2x/d2x/.github/workflows/org-login-slack.yml@cumulusci-next-snapshots
        with:
            environment: ${{ inputs.org }}
            slack_username: ${{ github.event.inputs.slack_username }}
        secrets:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
