name: Request Org Login Url to Slack DM
on:
    push:
        branches:
            - main
            - jlantz/fix-request-login-url
    workflow_dispatch:
        inputs:
            org:
                description: "The name of the org to get the login URL for. NOTE: Do not select orgs staring with `Snapshot:`"
                required: true
                type: environment
            slack_username:
                description: "The Slack username to send the DM to"
                required: true
                type: string
jobs:
    send-login-url:
        runs-on: ubuntu-latest
        steps:
            - name: Check SFDX_AUTH_URL
              run: |
                if [ -z "${{ secrets.SFDX_AUTH_URL }}" ]; then
                  echo "Error: SFDX_AUTH_URL is not set."
                  exit 1
                fi
            - name: Generate Login URL for ${{ inputs.org }}
              run: d2x sf auth login | tail -1 > login_url.txt
              env:
                SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
            - name: Send Slack DM
              run: |
                login_url=$(cat login_url.txt)
                rm login_url.txt
                curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
                     -H "Content-Type: application/json" \
                     -d '{
                       "channel": "@${{ inputs.slack_username }}",
                       "text": "Here is your Salesforce login URL for ${{ inputs.org }}: $login_url"
                     }' \
                     https://slack.com/api/chat.postMessage
